---
title: "county.Rmd"
author: "Samruddhi Naik"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidycensus)
library(tidyverse)
library(ggthemes)
library(tigris)
```

The map we made shows the racial demographic of Middlesex County, Massachusetts.


```{r}
load_variables(2018, "acs5") |> 
  filter(concept == "RACE") 

racevars <- c("B02001_002", "B02001_003", "B02001_005", "B03003_003", "B02001_004" )
```

```{r}
county_data <- get_acs(geography = "tract", 
                       variables = racevars, 
                       year = 2018, state = "Massachusetts",
                       county = "Middlesex", geometry = TRUE,
                       summary_var = "B02001_001") |>
                  mutate(Percent = (estimate/summary_est)*100) |>
                  mutate(variable = if_else(variable == "B02001_002", "White", variable)) |> 
                  mutate(variable = if_else(variable == "B02001_003", "Black", variable)) |>
                  mutate(variable = if_else(variable == "B02001_005", "Asian", variable)) |>
                  mutate(variable = if_else(variable == "B03003_003", "Hispanic", variable)) |>
                  mutate(variable = if_else(variable == "B02001_004", "Native American", variable))


county_data |> 
  ggplot(aes(fill = Percent, color = Percent)) + 
    geom_sf() +
    facet_wrap(~variable) +
    scale_fill_viridis_c(direction = -1) +
    scale_color_viridis_c(direction = -1) +
    labs(title = "Racial Geography of Middlesex County, Massachusetts",
         fill = "Percent",
         caption = "Source: American Community Survey 2014-2018") +
    theme_void()

```

