---
title: "rural.Rmd"
author: "Samruddhi Naik"
date: '2022-06-30'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidycensus)
library(tidyverse)
library(ggthemes)
library(tigris)
```

The map that we made shows how rural the US states are.

```{r}
rural <- get_decennial(geography = "state",
              variables = c("P001001", "P002005"),
              year = 2010, output = "wide",
              geometry = TRUE) 

rural |> 
  filter(!NAME %in% c("Alaska", "Hawaii", "Puerto Rico")) |>
  ggplot(aes(fill = (P002005/P001001)*100)) +
    geom_sf() +
    scale_fill_viridis_c(option = "plasma", direction = -1) +
    labs(title = "Rural geography of the United States", 
         x = NULL, y = NULL,
         fill = "Percent", 
         caption = "Source: Census 2010") +
    theme_void()

```

```{r}
rural_shifted <- get_decennial(geography = "state",
              variables = c("P001001", "P002005"),
              year = 2010, output = "wide",
              geometry = TRUE) |> 
          shift_geometry()

rural_shifted |>
  ggplot(aes(fill = (P002005/P001001)*100)) +
    geom_sf() +
    scale_fill_viridis_c(option = "plasma", direction = -1) +
    labs(title = "Rural geography of the United States", 
         x = NULL, y = NULL,
         fill = "Percent", 
         caption = "Source: Census 2010") +
    theme_void()

```
